# Each project update log and time max reload 5 offical
#  

[release]
main.update_info = { "1.0.2" = "", "1.0.4" = "Add the setup.py", "1.0.6" = "Fix some bug.\nAdd the Chinese documents.Update the update -- 1.1.0", "1.0.7" = "Modify some code.\nUpdate some packages:\n\tupdate -- 1.1.1\n\tdatalist_conversion -- 1.1.0", "1.1.0" = "Modify some code.", "1.2.0" = "Fix some bug.\nAdd two moudles:\n\tpassword:Encrypt your texts.This moudle is not completed.\n\ttypes:Some types.\nNow dec can used.\n\tUpdate the update -- 1.1.2." }
main.version = "1.2.0"
main.update_time = { "1.0.2" = 2025-03-20, "1.0.4" = 2025-03-20, "1.0.6" = 2025-03-22, "1.0.7" = 2025-03-23, "1.1.0" = 2025-04-05 }

unit.version = "1.2.1"
unit.update_info = { "1.0.0" = "", "1.0.1" = "Add the ABCUnit,recommed all the class unit(new unit type) use this type.", "1.1.0" = "Delete the ABCUnit.", "1.2.0" = "Add 'Points',Simply get the point.", "1.2.1" = "Add the ABCUnit again.", will = "Add Weight and time UnitClass." }
unit.update_time = { "1.0.0" = 2025-03-20, "1.0.1" = 2025-03-22, "1.1.0" = 2025-03-23, "1.2.0" = 2025-04-08, "1.2.1" = 2025-04-09 }

database_convert.version = "1.1.1"
database_convert.update_info = { "1.0.0" = "", "1.1.0" = "Add pickle,yaml,toml convert.", "1.1.1" = "Fix some bug." }
database_convert.update_time = { "1.0.0" = 2025-03-20, "1.1.0" = 2025-03-23, "1.1.1" = 2025-04-12 }

dec.version = "1.0.0"
dec.update_info = { "1.0.0" = "", "1.1.0" = "Add calc." }
dec.update_time = { "1.0.0" = 2025-04-05, "1.1.0" = 0 }

[pre-release]
main.version = "1.2.0"
main.update_info = { "1.2.0a1" = "Fix some bug.\nAdd two moudles:\n\tpassword:Encrypt your texts.This moudle is not completed.\n\ttypes:Some types.\nNow dec can used.\n\tUpdate the update -- 1.1.2.", "1.2.0a2" = "Fix some bug.\nupdate the science -- 1.2.0.", "1.2.0b1" = "Fix some bug.\nUpdate the science -- 1.2.1.\nAdd lib:advancedlib:Some expansions of bulit-in functions.\nAdd tools:moudle:Getsome operations of import.", "1.2.0rc2" = "Modify some code.", "1.2.0" = "Rename the datalist_conversion -- database_convert.", "1.2.0rc3" = "Add more update log."}
main.update_time = { "1.2.0a1" = 2025-04-07, "1.2.0a2" = 2025-04-08, "1.2.0b1" = 2025-04-09, "1.2.0rc2" = 2025-04-10, "1.2.0rc3" = 2025-04-12 }
