# Each project update log and time max reload 5 offical 
[release]
main.version = "1.2.0"
main.update_info."1.0.4" = "Add the setup.py" 
main.update_time."1.0.4" = 2025-03-20 
main.update_info."1.0.6" = "Fix some bug.\nAdd the Chinese documents.Update the update -- 1.1.0"
main.update_time."1.0.6" = 2025-03-22
main.update_info."1.0.7" = "Modify some code.\nUpdate the update -- 1.1.1"
main.update_time."1.0.7" = 2025-03-23
main.update_info."1.1.0" = "Modify some code."
main.update_time."1.1.0" = 2025-04-05
main.update_info."1.2.0" = "Fix some bug.\nAdd two moudles:\n\tpassword:Encrypt your texts.This moudle is not completed.\n\ttypes:Some types.\nNow dec can used.\n\tUpdate the update -- 1.1.2."
main.update_time."1.2.0" = ""

[pre-release]
main.version = "1.2.0b1"
main.update_info."1.2.0a1" = "Fix some bug.\nAdd two moudles:\n\tpassword:Encrypt your texts.This moudle is not completed.\n\ttypes:Some types.\nNow dec can used.\n\tUpdate the update -- 1.1.2."
main.update_time."1.2.0a1" = 2025-04-07
main.update_info."1.2.0a2" = "Fix some bug.\nupdate the science -- 1.2.0."
main.update_time."1.2.0a2" = 2025-04-08
main.update_info."1.2.0b1" = "Fix some bug.\nUpdate the science -- 1.2.1.\nAdd lib:advancedlib:Some expansions of bulit-in functions.\nAdd tools:moudle:Getsome operations of import."
main.update_time."1.2.0b2" = 2025-04-08

unit.version = "1.2.1"
unit.update_info."1.0.0" = ""
unit.update_info."1.0.1" = "Add the ABCUnit,recommed all the class unit(new unit type) use this type."
unit.update_info."1.1.0" = "Delete the ABCUnit."
unit.update_info."1.2.0" = "Add 'Points',Simply get the point."
unit.update_info."1.2.1" = "Add the ABCUnit again."
unit.update_time."1.0.0" =  2025-03-20
unit.update_time."1.0.1" =  2025-03-22
unit.update_time."1.1.0" =  2025-03-23
unit.update_time."1.2.0" =  2025-04-08
unit.update_time."1.2.1" =  2025-04-09