# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
   
name: Python package publish

on:
  workflow_dispatch:

jobs:
  Build and publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install build dependencies
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build package
      run: python -m build

    - name: Publish to TestPyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TESTPYPI_API_TOKEN }}
      run: twine upload dist/* --repository testpypi