# This workflow will install Python dependencies, run tests and lint with a variety of Python versions.
   
name: build_and_publish

on:
  push:
    branches: [ "master", "develop", "2.0-update" ]
  pull_request:
    branches: [ "develop", "2.0-update" ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with: 
        name: dist-package
        path: |
          dist/*.whl
          dist/*.tar.gz

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*